# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-TableExtract
version:      2.07
version_from: lib/HTML/TableExtract.pm
installdirs:  site
requires:
    HTML::ElementTable:            1.13
    HTML::Parser:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
